modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Vazkii/Neat"
license="Creative Commons 3.0 BY-NC-SA"

[[mods]]
modId="neat"
displayName="Neat"
version="1.0"
authors="Vazkii"
description='''
Minimalistic Functional Unit Plates for the modern Minecrafter
'''
